// packages/angular/src/tag-cloud.component.ts
import {
  EventEmitter,
  Output,
  AfterViewChecked,
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  ViewEncapsulation,
} from '@angular/core';
import {
  prepareTags,
  TagCloudLayout,
  type Fill,
  type PreparedTag,
  type PrepareOptions,
  type TagCloudItem,
} from '@opentagcloud/core';

/**
 * Angular adapter: renders the tags (SSR-safe — the scatter is
 * deterministically seeded, so server and hydrated markup match) and hands
 * layout to `TagCloudLayout` after the view initializes. The host element
 * itself is the cloud container, so give `<otc-tag-cloud>` a sized parent.
 *
 * Styles are injected at runtime by the layout engine. For a styled no-JS/SSR
 * fallback, also add `@opentagcloud/core/styles.css` to your `angular.json`
 * `styles` array (the runtime injection then dedupes to a no-op).
 */
@Component({
  selector: 'otc-tag-cloud',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  host: { class: 'otc-cloud' },
  template: `
    @for (p of prepared; track p.key) {
      @if (p.tag === 'a') {
        <a
          [attr.href]="p.href"
          [class]="p.className"
          [attr.title]="p.title ?? null"
          [attr.aria-label]="p.ariaLabel ?? null"
          [attr.data-fs]="p.fontPx"
          [attr.data-weight]="p.weight"
          [attr.data-key]="p.key"
          [style.font-size.px]="p.fontPx"
          [style.opacity]="p.opacity"
          [style.--otc-tag-color]="p.item.color ?? null"
          (click)="tagClick.emit({ item: p.item, event: $event })"
        >
          @for (part of p.parts; track $index) {
            @if (part.nowrap) {
              <span class="otc-nb">{{ part.text }}</span>
            } @else {
              <ng-container>{{ part.text }}</ng-container>
            }
          }
        </a>
      } @else if (p.tag === 'button') {
        <button
          type="button"
          [class]="p.className"
          [attr.title]="p.title ?? null"
          [attr.aria-label]="p.ariaLabel ?? null"
          [attr.data-fs]="p.fontPx"
          [attr.data-weight]="p.weight"
          [attr.data-key]="p.key"
          [style.font-size.px]="p.fontPx"
          [style.opacity]="p.opacity"
          [style.--otc-tag-color]="p.item.color ?? null"
          (click)="tagClick.emit({ item: p.item, event: $event })"
        >
          @for (part of p.parts; track $index) {
            @if (part.nowrap) {
              <span class="otc-nb">{{ part.text }}</span>
            } @else {
              <ng-container>{{ part.text }}</ng-container>
            }
          }
        </button>
      } @else {
        <span
          [class]="p.className"
          [attr.title]="p.title ?? null"
          [attr.aria-label]="p.ariaLabel ?? null"
          [attr.data-fs]="p.fontPx"
          [attr.data-weight]="p.weight"
          [attr.data-key]="p.key"
          [style.font-size.px]="p.fontPx"
          [style.opacity]="p.opacity"
          [style.--otc-tag-color]="p.item.color ?? null"
          (click)="tagClick.emit({ item: p.item, event: $event })"
        >
          @for (part of p.parts; track $index) {
            @if (part.nowrap) {
              <span class="otc-nb">{{ part.text }}</span>
            } @else {
              <ng-container>{{ part.text }}</ng-container>
            }
          }
        </span>
      }
    }
  `,
})
export class TagCloudComponent
  implements OnChanges, AfterViewInit, AfterViewChecked, OnDestroy
{
  /** The tags to lay out. */
  @Input({ required: true }) items: TagCloudItem[] = [];
  /** Font size (px) of the lightest tag. */
  @Input() minPx = 12;
  /** Font size (px) of the heaviest tag. */
  @Input() maxPx = 40;
  /** `'height'`/`'both'` also spreads terms to fill the container's height. */
  @Input() fill?: Fill;
  /** Opacity of the lightest tag (raise for WCAG contrast; 1 disables the fade). */
  @Input() minOpacity = 0.62;
  /** Accessible name per tag: true → "<label>, weight <weight>", or a custom fn. */
  @Input() ariaLabel?: PrepareOptions['ariaLabel'];
  /** Keep unchanged tags in place across item updates (see TagCloudLayoutOptions). */
  @Input() incremental = false;
  /** How tightly terms cluster, 0–1 (default 0.5): 0 spreads them evenly across the container, 1 packs them as tightly as possible around the centre. */
  @Input() density?: number;
  /** Fraction of a sized container to occupy, 0-1 (default 0.75). Lower values leave negative space; unrelated to `fill`. */
  @Input() fillFactor?: number;
  /**
   * Emitted when a tag is activated. Subscribing renders non-link tags as
   * `<button>`, so they are focusable and keyboard-operable.
   */
  @Output() readonly tagClick = new EventEmitter<{
    item: TagCloudItem;
    event: MouseEvent;
  }>();

  protected prepared: PreparedTag[] = [];
  private layout?: TagCloudLayout;
  private needsRefresh = false;

  constructor(private readonly host: ElementRef<HTMLElement>) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (
      changes['items'] ||
      changes['minPx'] ||
      changes['maxPx'] ||
      changes['minOpacity'] ||
      changes['ariaLabel']
    ) {
      this.prepared = prepareTags(this.items, {
        minPx: this.minPx,
        maxPx: this.maxPx,
        minOpacity: this.minOpacity,
        ariaLabel: this.ariaLabel,
        // `observed` is true once a consumer binds (tagClick)
        interactive: this.tagClick.observed,
      });
      // Re-pack once the view reflects the new tags (attach() packs the initial set).
      this.needsRefresh = !!this.layout;
    }
    if (changes['fill']) this.layout?.setFill(this.fill);
    if (changes['density']) this.layout?.setDensity(this.density);
    if (changes['fillFactor']) this.layout?.setFillFactor(this.fillFactor);
  }

  ngAfterViewInit(): void {
    // TagCloudLayout.attach() is a no-op without a DOM, so this is SSR-safe.
    this.layout = new TagCloudLayout(this.host.nativeElement, {
      fill: this.fill,
      incremental: this.incremental,
      density: this.density,
      fillFactor: this.fillFactor,
    });
    this.layout.attach();
  }

  ngAfterViewChecked(): void {
    if (this.needsRefresh) {
      this.needsRefresh = false;
      this.layout?.refresh();
    }
  }

  ngOnDestroy(): void {
    this.layout?.destroy();
    this.layout = undefined;
  }
}

// packages/solid/src/TagCloud.tsx
import {
  createEffect,
  createMemo,
  on,
  onCleanup,
  onMount,
  For,
} from 'solid-js';
import { Dynamic } from 'solid-js/web';
import {
  prepareTags,
  TagCloudLayout,
  type Fill,
  type PreparedTag,
  type PrepareOptions,
  type TagCloudItem,
} from '@opentagcloud/core';

export interface TagCloudProps {
  /** The tags to lay out. */
  items: TagCloudItem[];
  /** Font size (px) of the lightest tag. */
  minPx?: number;
  /** Font size (px) of the heaviest tag. */
  maxPx?: number;
  /**
   * `'height'`/`'both'` lets the cloud spread its terms to fill a taller
   * container (e.g. a grid-row sibling) so neighbours stay aligned.
   */
  fill?: Fill;
  /** Opacity of the lightest tag (raise for WCAG contrast; 1 disables the fade). */
  minOpacity?: number;
  /** Accessible name per tag: true → "<label>, weight <weight>", or a custom fn. */
  ariaLabel?: PrepareOptions['ariaLabel'];
  /** Keep unchanged tags in place across item updates (see TagCloudLayoutOptions). */
  incremental?: boolean;
  /** How tightly terms cluster, 0–1 (default 0.5): 0 spreads them evenly across the container, 1 packs them as tightly as possible around the centre. */
  density?: number;
  /** Fraction of a sized container to occupy, 0-1 (default 0.75). Lower values leave negative space; unrelated to `fill`. */
  fillFactor?: number;
  /**
   * Called when a tag is activated. Supplying it renders non-link tags as
   * `<button>`, so they are focusable and keyboard-operable.
   */
  onTagClick?: (item: TagCloudItem, event: MouseEvent) => void;
  /** Extra class(es) on the cloud container. */
  class?: string;
}

// Hyphenated words render inside .otc-nb (white-space: nowrap) so lines never
// break at a hyphen; the DOM text stays byte-identical to the label.
function tagContent(p: PreparedTag) {
  return (
    <For each={p.parts}>
      {(part) =>
        part.nowrap ? <span class="otc-nb">{part.text}</span> : part.text
      }
    </For>
  );
}

/**
 * SolidJS adapter: renders the tags (SSR-safe — the scatter is
 * deterministically seeded, so server and hydrated markup match) and hands
 * layout to `TagCloudLayout` on mount. Give the cloud a sized parent.
 *
 * Ships uncompiled Solid JSX under the `solid` export condition — compiled by
 * vite-plugin-solid (used by every Solid/SolidStart app) like your own code.
 */
export function TagCloud(props: TagCloudProps) {
  let root!: HTMLDivElement;
  let layout: TagCloudLayout | undefined;

  const prepared = createMemo(() =>
    prepareTags(props.items, {
      minPx: props.minPx ?? 12,
      maxPx: props.maxPx ?? 40,
      minOpacity: props.minOpacity ?? 0.62,
      ariaLabel: props.ariaLabel,
      interactive: !!props.onTagClick,
    }),
  );

  onMount(() => {
    layout = new TagCloudLayout(root, {
      fill: props.fill,
      incremental: props.incremental,
      density: props.density,
      fillFactor: props.fillFactor,
    });
    layout.attach();
    onCleanup(() => {
      layout?.destroy();
      layout = undefined;
    });
  });

  // Re-pack when the rendered tags change; attach() already packed the initial set.
  createEffect(on(prepared, () => layout?.refresh(), { defer: true }));
  createEffect(
    on(
      () => props.fill,
      (fill) => layout?.setFill(fill),
      { defer: true },
    ),
  );
  createEffect(
    on(
      () => props.density,
      (density) => layout?.setDensity(density),
      { defer: true },
    ),
  );
  createEffect(
    on(
      () => props.fillFactor,
      (fillFactor) => layout?.setFillFactor(fillFactor),
      { defer: true },
    ),
  );

  return (
    <div
      ref={root}
      class={props.class ? `otc-cloud ${props.class}` : 'otc-cloud'}
    >
      <For each={prepared()}>
        {(p) => (
          <Dynamic
            component={p.tag}
            class={p.className}
            href={p.href}
            type={p.tag === 'button' ? 'button' : undefined}
            title={p.title}
            aria-label={p.ariaLabel}
            style={p.style}
            data-fs={p.fontPx}
            data-weight={p.weight}
            data-key={p.key}
            onClick={(e: MouseEvent) => props.onTagClick?.(p.item, e)}
          >
            {tagContent(p)}
          </Dynamic>
        )}
      </For>
    </div>
  );
}
